### PR TITLE
ZIP file updates

### PR DESCRIPTION
**Pull request by OpenGlobe**
Added fonts to the ZIP file so they don't have to be downloaded somewhere separately, and added a bit of explanatory text.  Use if helpful -

### CODE REVIEW

**Comment by OpenGlobe** [comment]
https://github.com/18F/brand/issues/66

**Comment by jenniferthibault** [comment]
Thank you so much @OpenGlobe ! :boom:

**Comment by maya** [comment]
Some people will have already downloaded the fonts, so we don't want people to download them twice. I think some documentation explaining that it's necessary to download the fonts to use the slides, should do the trick.

**Comment by jenniferthibault** [comment]
I see what you're saying Maya, but it doesn't really hurt to download the fonts more than once. I'm starting to see the Keynote file package like an InDesign file package - you want all the assets it requires to be zipped in and ready to launch in one place, instead of needing to download things in multiple places. In this case, it's only the additional fonts that are needed to make a full package. It's similar to how we're zipping in the color palette.  

If a user already has these fonts installed, they won't get an error when opening the keynote, so I doubt they would try to re-install the fonts. We're meeting up today to talk about some brand stuff, so I'll come back and update this after seeing what other folks think.

**Comment by jenniferthibault** [comment]
We're going to use this structure of including fonts with the Keynote package — it will make one more step for us if we make changes to the fonts, but I think it ultimately makes it easier for users who come to the site only for templates. Thanks again @OpenGlobe !

**Comment by OpenGlobe** [comment]
Cool!  Glad it helped @jenniferthibault !

**Pull request merged**
