### PR TITLE
link to the frontmatter template

### PR DESCRIPTION
**Pull request by afeld**

### CODE REVIEW

**Comment by cmajel** [comment]
@afeld, thanks for submitting a suggestion. Can you tell us a bit more about why you are suggesting this change?

**Comment by afeld** [comment]
I've seen that front matter template used a bunch of places, but seems it might have been mostly spread through word of mouth? The idea here is to highlight it as a thing that 18F uses for documents often. @coreycaitlin may be able to say more about the motivation behind the creation in the first place, if that's what you're asking.

**Comment by cmajel** [comment]
@afeld thanks for the suggestion. A few things:
* I know @Dahianna has been working on TTS assets, so I am not sure that we want the 18F templates to be used by all TTS (especially if there is going to be a branded option for them).

* For the front matter template, it may be helpful to add more context around when to use it and why. Could you or @coreycaitlin provide some context on how to use it so we can fold it in to the page content?

**Comment by afeld** [comment]
I'm just the messenger - will let y'all decide what to do ☁️

**Comment by Dahianna** [comment]
Decided to keep this template in the drive for now

**Pull request closed without merging**
