### PR TITLE
Configs Updates

### PR DESCRIPTION
**Pull request by igorkorenfeld**
This PR sets up the search handle (and thereby the search input) and the Private Eye script for locked links.

### CODE REVIEW

**Comment by Dahianna** [comment]
search works for me and private eye appears in most links. The only one I noticed were it wasn't working was in the [logo page. ](https://federalist-9413b3a7-6641-4d7e-bf2d-fd9440417d07.app.cloud.gov/preview/18f/brand/ik-configs/logo/)The link for the Slack channel is broken `Do ask in (#18f-branding)[https://18f.slack.com/archives/18f-branding] when you have questions.`

**Review by Dahianna — COMMENTED** [review]
Private eye not working on slack channel link in logo page

**Comment by igorkorenfeld** [comment]
Thanks @Dahianna ! Fixed the broken link and the private eye and Slack icons should show up correctly now.

**Review by cmajel — APPROVED** [review]
@igorkorenfeld I took a look at this branch on federalist and verified the the search works as expected and I'm seeing 🔒 links for private links. 👍

**Pull request merged**
