### PR TITLE
Setup footer

### PR DESCRIPTION
**Pull request by igorkorenfeld**
This PR adds a footer that matches the other 18F guides 

👀  [Preview](https://federalist-9413b3a7-6641-4d7e-bf2d-fd9440417d07.app.cloud.gov/preview/18f/brand/ik-footer/)

### CODE REVIEW

**Comment by igorkorenfeld** [comment]
Discussed with @Dahianna , need to change to newer version of the identifier like on 18F site

**Comment by Dahianna** [comment]
You can find code and more info on [USWDS site](https://designsystem.digital.gov/components/identifier/)

**Comment by igorkorenfeld** [comment]
@Dahianna I've updated the footer to the new version of the identifier. Since that only includes that GSA logo, I added that 18F logo to the header now.

**Comment by Dahianna** [comment]
looks good! Thanks Igor!

**Pull request merged**
